[theme]
base = "light"

primaryColor = "#c4007a"

backgroundColor = "#F7F8FA"

secondaryBackgroundColor = "#18112E"

textColor = "#0F172A"

font = "sans"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
